import { PHOTOREAL_SKIN } from "@/lib/promptQuality";
import type { CharacterSheetQuality, CharacterSheetSection, CharacterSheetSlot } from "@/lib/characterSheet-types";

/** Display order + section header text, in the same order the composited
 * poster lays them out. */
export const SECTION_ORDER: CharacterSheetSection[] = ["angles", "poses", "details", "expressions", "lighting"];

export const SECTION_LABELS: Record<CharacterSheetSection, string> = {
  angles: "Head Angles",
  poses: "Full Body Poses",
  details: "Details",
  expressions: "Expressions",
  lighting: "Lighting References",
};

/** Shown on the "Generate sheet" button while that section still has any
 * non-terminal slot — e.g. "Rendering angles…". */
export const SECTION_STAGE_LABELS: Record<CharacterSheetSection, string> = {
  angles: "Rendering angles…",
  poses: "Mapping poses…",
  details: "Capturing details…",
  expressions: "Rendering expressions…",
  lighting: "Building lighting…",
};

interface SlotTemplate {
  /** Stable, never reused as an array index — selection state (ShotPicker,
   * the request body) references shots by this id so it survives the
   * catalog being reordered or trimmed. */
  id: string;
  section: CharacterSheetSection;
  label: string;
  promptSuffix: string;
}

/**
 * The full catalog of available shots — NOT all generated by default (see
 * DEFAULT_SELECTED_SLOT_IDS). Deterministic/templated, NOT LLM-planned (24
 * near-identical prompts don't need a planner — see the Character Sheet
 * plan). Declaration order = poster layout order within each section.
 */
const SLOT_TEMPLATES: SlotTemplate[] = [
  // Head Angles
  { id: "angle-front", section: "angles", label: "Front", promptSuffix: "studio headshot, facing directly forward, neutral expression, plain seamless background" },
  { id: "angle-3-4-left", section: "angles", label: "3/4 Left", promptSuffix: "studio headshot, head turned three-quarters to the left, plain seamless background" },
  { id: "angle-3-4-right", section: "angles", label: "3/4 Right", promptSuffix: "studio headshot, head turned three-quarters to the right, plain seamless background" },
  { id: "angle-profile-left", section: "angles", label: "Profile Left", promptSuffix: "studio headshot, full left profile view, plain seamless background" },
  { id: "angle-profile-right", section: "angles", label: "Profile Right", promptSuffix: "studio headshot, full right profile view, plain seamless background" },
  // Full Body Poses
  { id: "pose-standing-front", section: "poses", label: "Standing Front", promptSuffix: "full body studio shot, standing straight facing camera, plain seamless background" },
  { id: "pose-walking-forward", section: "poses", label: "Walking Forward", promptSuffix: "full body studio shot, mid-stride walking toward camera, plain seamless background" },
  { id: "pose-3-4-standing-left", section: "poses", label: "3/4 Standing Left", promptSuffix: "full body studio shot, standing at a three-quarter angle to the left, plain seamless background" },
  { id: "pose-looking-over-shoulder", section: "poses", label: "Looking Over Shoulder", promptSuffix: "full body studio shot, back mostly to camera, looking back over one shoulder, plain seamless background" },
  { id: "pose-sitting-on-stool", section: "poses", label: "Sitting on Stool", promptSuffix: "full body studio shot, seated on a plain stool, relaxed posture, plain seamless background" },
  { id: "pose-leaning-against-wall", section: "poses", label: "Leaning Against Wall", promptSuffix: "full body studio shot, leaning casually against a plain wall, plain seamless background" },
  // Details
  { id: "detail-eyes", section: "details", label: "Eyes", promptSuffix: "extreme close-up macro shot of the eyes only, sharp focus, plain background" },
  { id: "detail-profile", section: "details", label: "Profile", promptSuffix: "close-up macro shot of the facial profile silhouette, sharp focus, plain background" },
  { id: "detail-distinguishing-mark", section: "details", label: "Distinguishing Mark", promptSuffix: "close-up macro shot highlighting the character's most distinguishing physical feature, sharp focus, plain background" },
  // Expressions
  { id: "expr-neutral", section: "expressions", label: "Neutral", promptSuffix: "studio headshot, calm neutral expression, plain seamless background" },
  { id: "expr-soft-smile", section: "expressions", label: "Soft Smile", promptSuffix: "studio headshot, soft warm smile, plain seamless background" },
  { id: "expr-serious", section: "expressions", label: "Serious", promptSuffix: "studio headshot, serious intense expression, plain seamless background" },
  { id: "expr-thoughtful", section: "expressions", label: "Thoughtful", promptSuffix: "studio headshot, thoughtful contemplative expression looking slightly off-camera, plain seamless background" },
  { id: "expr-surprised", section: "expressions", label: "Surprised", promptSuffix: "studio headshot, genuinely surprised expression, plain seamless background" },
  { id: "expr-laughing", section: "expressions", label: "Laughing", promptSuffix: "studio headshot, mid-laugh candid expression, plain seamless background" },
  // Lighting References
  { id: "light-daylight", section: "lighting", label: "Natural Daylight", promptSuffix: "studio headshot lit with bright even natural daylight, plain seamless background" },
  { id: "light-window", section: "lighting", label: "Soft Window Light", promptSuffix: "studio headshot lit with soft diffused window light from one side, plain seamless background" },
  { id: "light-golden-hour", section: "lighting", label: "Golden Hour", promptSuffix: "studio headshot lit with warm golden-hour side lighting, plain seamless background" },
  { id: "light-indoor-studio", section: "lighting", label: "Indoor Studio", promptSuffix: "studio headshot lit with a classic three-point indoor studio lighting setup, plain seamless background" },
];

/** What ShotPicker/HowItWorksTab render — id/section/label only, no prompt
 * text (the explainer tab just needs to show what the shots are, not how
 * they're actually prompted). */
export const SLOT_CATALOG: { id: string; section: CharacterSheetSection; label: string }[] = SLOT_TEMPLATES.map(
  ({ id, section, label }) => ({ id, section, label })
);

/** The sheet's starting selection — a curated ~10 shots spanning every
 * section, well within the user's requested 8-12 range. ShotPicker lets
 * this be freely customized (added to or trimmed) before generating; this
 * is just where it starts. */
export const DEFAULT_SELECTED_SLOT_IDS: string[] = [
  "angle-front",
  "angle-3-4-left",
  "pose-standing-front",
  "pose-walking-forward",
  "detail-eyes",
  "expr-neutral",
  "expr-soft-smile",
  "expr-serious",
  "light-daylight",
  "light-golden-hour",
];

/** muapi's flux-pulid endpoint has no explicit resolution parameter in
 * Revolio's model registry (see src/lib/models.ts) — there's no real "1K vs
 * 2K" knob to pass through. The closest genuine, controllable difference is
 * aspect ratio/framing, so "quality" maps to that instead of a fabricated
 * resolution toggle: Compact stays a tighter square crop, Studio renders a
 * fuller 4:3 frame. Both are honestly real settings sent to the model, just
 * not literally pixel-resolution tiers. */
export function aspectRatioForQuality(quality: CharacterSheetQuality): string {
  return quality === "studio" ? "4:3" : "1:1";
}

/** Builds the real slots for just the selected shot ids, once the anchor
 * phrase is known (after the vision-LLM metadata call resolves) — each
 * slot's prompt is `${anchorPhrase}, ${promptSuffix}, ${PHOTOREAL_SKIN}`.
 * Falls back to the default selection if `selectedIds` is empty (a request
 * with nothing picked shouldn't silently generate zero shots). */
export function buildCharacterSheetSlots(anchorPhrase: string, selectedIds: string[]): CharacterSheetSlot[] {
  const ids = selectedIds.length > 0 ? selectedIds : DEFAULT_SELECTED_SLOT_IDS;
  const idSet = new Set(ids);
  // Preserve SLOT_TEMPLATES' own declaration order (poster layout order),
  // not the order ids happened to arrive in.
  const chosen = SLOT_TEMPLATES.filter((t) => idSet.has(t.id));
  return chosen.map((t, index) => ({
    index,
    section: t.section,
    label: t.label,
    prompt: `${anchorPhrase}, ${t.promptSuffix}, ${PHOTOREAL_SKIN}`,
    status: "queued",
  }));
}

/** Which section's stage label the "Generate sheet" button should currently
 * show — the first section (in poster order) that still has a non-terminal
 * slot, or null once everything's settled. */
export function currentSection(slots: CharacterSheetSlot[]): CharacterSheetSection | null {
  for (const section of SECTION_ORDER) {
    const inSection = slots.filter((s) => s.section === section);
    if (inSection.some((s) => s.status === "queued" || s.status === "processing")) return section;
  }
  return null;
}
