import type { ModelConfig } from "./models";

// September 2026 additions. Endpoint names and input shapes were checked
// against MuAPI's public GET /models and GET /models/{name} responses.
// The authenticated schema route supplies the full live enum/range controls.
const HORSE_RATIOS = ["16:9", "9:16", "1:1", "4:3", "3:4"];
const MUSE_RATIOS = ["1:1", "16:9", "9:16", "4:3", "3:4", "21:9"];
const CATALOG_BASE_COST_USD: Record<string, number> = {
  "muse-image-text-to-image": 0.02,
  "muse-image-edit": 0.02,
  "qwen3-image-to-image": 0.03,
  "flux-kontext-dev-t2i": 0.02,
  "flux-kontext-dev-i2i": 0.02,
  "happy-horse-1-text-to-video": 0.9,
  "happy-horse-1-image-to-video": 0.9,
  "happy-horse-1-reference-to-video": 1.05,
  "happy-horse-1-video-edit": 1.05,
  "happy-horse-1.1-text-to-video": 0.7,
  "happy-horse-1.1-image-to-video": 0.7,
  "happy-horse-1.1-reference-to-video": 0.7,
  "happy-horse-1.1-video-edit": 0.7,
  "minimax-h3-image-to-video-spicy": 0.29,
  "minimax-h3-max-text-to-video": 0.26,
  "minimax-h3-max-image-to-video": 0.26,
  "minimax-h3-max-turbo-text-to-video": 0.13,
  "minimax-h3-max-turbo-image-to-video": 0.13,
  "minimax-h3-max-reference-to-video": 0.52,
  "minimax-h3-open-reference-to-video": 0.33,
  "ltx-2.5-text-to-video": 0.65,
  "ltx-2.5-image-to-video": 0.65,
  "flux-3-video-extend": 0.25,
  "wan3.0-spicy-reference-to-video": 0.55,
  "seedance-2-motion-control": 1,
  "seedance-2.5-motion-control": 1.5,
  "seedance-2.5-intl-motion-control": 1.65,
  "seedance-2.5-spicy-motion-control": 1.65,
  "seedance-2-mini-spicy-omni-reference": 0.75,
  "seedance-2-spicy-omni-reference": 1.5,
  "seedance-2-spicy-omni-reference-fast": 1.05,
  "seedance-2.5-spicy-omni-reference": 1.87,
};

export const NEW_MUAPI_MODELS: ModelConfig[] = ([
  {
    id: "muse-image", label: "Muse Image", provider: "Meta", category: "image", mode: "t2i",
    endpoint: "muse-image-text-to-image", maxReferences: 0,
    aspectRatios: MUSE_RATIOS, defaultAspectRatio: "1:1", badge: "New",
    tagline: "Generate images from text with Meta Muse",
  },
  {
    id: "muse-image-edit", label: "Muse Image Edit", provider: "Meta", category: "image", mode: "i2i",
    endpoint: "muse-image-edit", imageInputKey: "images_list", maxReferences: 10,
    requiresReferenceInput: true,
    aspectRatios: MUSE_RATIOS, defaultAspectRatio: "1:1", badge: "New",
    tagline: "Edit and combine up to 10 reference images",
  },
  {
    id: "qwen3-image-edit", label: "Qwen3 Image Edit", provider: "Qwen", category: "image", mode: "i2i",
    endpoint: "qwen3-image-to-image", imageInputKey: "images_list", maxReferences: 3,
    requiresReferenceInput: true,
    aspectRatios: ["1:1", "3:2", "2:3", "4:3", "3:4", "16:9", "9:16", "21:9"],
    defaultAspectRatio: "1:1", badge: "New", tagline: "Reference edits with prompt expansion and negative prompts",
  },
  {
    id: "flux-kontext-dev", label: "Flux Kontext Dev", provider: "Black Forest Labs",
    category: "image", mode: "t2i", endpoint: "flux-kontext-dev-t2i", maxReferences: 0,
    supportsNumImages: true, maxNumImages: 4,
    aspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4", "3:2", "2:3", "21:9", "9:21"],
    defaultAspectRatio: "1:1", badge: "New", tagline: "Fast contextual image generation",
  },
  {
    id: "flux-kontext-dev-edit", label: "Flux Kontext Dev Edit", provider: "Black Forest Labs",
    category: "image", mode: "i2i", endpoint: "flux-kontext-dev-i2i",
    imageInputKey: "images_list", maxReferences: 10, requiresReferenceInput: true,
    supportsNumImages: true, maxNumImages: 4,
    aspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4", "3:2", "2:3", "21:9", "9:21"],
    defaultAspectRatio: "1:1", badge: "New", tagline: "Edit with up to 10 reference images",
  },
  ...(["1", "1.1"] as const).flatMap((version) => {
    const id = `happy-horse-${version}`;
    const label = `Happy Horse ${version}`;
    return [
      { id: `${id}-t2v`, label: `${label} Text to Video`, provider: "Happy Horse", category: "video" as const,
        mode: "t2v" as const, endpoint: `${id}-text-to-video`, maxReferences: 0,
        aspectRatios: HORSE_RATIOS, defaultAspectRatio: "16:9", badge: "New",
        tagline: "Expressive video from a written prompt" },
      { id: `${id}-i2v`, label: `${label} Image to Video`, provider: "Happy Horse", category: "video" as const,
        mode: "i2v" as const, endpoint: `${id}-image-to-video`, imageInputKey: "images_list" as const,
        maxReferences: 1, requiresReferenceInput: true,
        aspectRatios: HORSE_RATIOS, defaultAspectRatio: "16:9", badge: "New",
        tagline: "Animate a source image" },
      { id: `${id}-reference`, label: `${label} Reference to Video`, provider: "Happy Horse", category: "video" as const,
        mode: "i2v" as const, endpoint: `${id}-reference-to-video`, imageInputKey: "images_list" as const,
        maxReferences: 9, requiresReferenceInput: true,
        aspectRatios: HORSE_RATIOS, defaultAspectRatio: "16:9", badge: "New",
        tagline: "Generate video with up to 9 image references" },
      { id: `${id}-edit`, label: `${label} Video Edit`, provider: "Happy Horse", category: "video" as const,
        mode: "v2v" as const, endpoint: `${id}-video-edit`, maxReferences: 5, requiresVideoInput: true,
        supportsKeepSound: false, badge: "New", tagline: "Edit footage with text and reference images" },
    ];
  }),
  {
    id: "minimax-h3-spicy-i2v", label: "MiniMax H3 Spicy Image to Video", provider: "MiniMax",
    category: "video", mode: "i2v", endpoint: "minimax-h3-image-to-video-spicy",
    imageInputKey: "image_url", maxReferences: 1, requiresReferenceInput: true,
    supportsStartEndFrame: true,
    endFrameFieldName: "last_image", badge: "New", tagline: "Animate a first frame with optional end frame",
  },
  ...(["", "-turbo"] as const).flatMap((variant) => [
    { id: `minimax-h3-max${variant}-t2v`, label: `MiniMax H3 Max${variant ? " Turbo" : ""} Text to Video`,
      provider: "MiniMax", category: "video" as const, mode: "t2v" as const,
      endpoint: `minimax-h3-max${variant}-text-to-video`, maxReferences: 0,
      aspectRatios: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
      defaultAspectRatio: "16:9", badge: "New", tagline: "High-fidelity video with native audio" },
    { id: `minimax-h3-max${variant}-i2v`, label: `MiniMax H3 Max${variant ? " Turbo" : ""} Image to Video`,
      provider: "MiniMax", category: "video" as const, mode: "i2v" as const,
      endpoint: `minimax-h3-max${variant}-image-to-video`, imageInputKey: "image_url" as const,
      maxReferences: 1, supportsStartEndFrame: true, endFrameFieldName: "end_image_url",
      badge: "New", tagline: "Animate a frame with optional end-frame guidance" },
  ]),
  {
    id: "minimax-h3-max-reference", label: "MiniMax H3 Max Reference to Video", provider: "MiniMax",
    category: "video", mode: "i2v", endpoint: "minimax-h3-max-reference-to-video",
    imageInputKey: "reference_images", maxReferences: 12,
    maxCombinedReferences: 12, maxVideoReferences: 12, requiresReferenceInput: true,
    aspectRatios: ["adaptive", "21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
    defaultAspectRatio: "adaptive", badge: "New", tagline: "Blend image, video and audio references",
  },
  {
    id: "minimax-h3-open-reference", label: "MiniMax H3 Open Reference to Video", provider: "MiniMax",
    category: "video", mode: "omni", endpoint: "minimax-h3-open-reference-to-video",
    imageInputKey: "images_list", maxReferences: 3, badge: "New",
    tagline: "Guide video with image, video and audio references",
  },
  {
    id: "ltx-2.5-t2v", label: "LTX 2.5 Text to Video", provider: "Lightricks", category: "video",
    mode: "t2v", endpoint: "ltx-2.5-text-to-video", maxReferences: 0,
    aspectRatios: ["16:9", "9:16"], defaultAspectRatio: "16:9", badge: "New",
    tagline: "Generate video from text up to 4K",
  },
  {
    id: "ltx-2.5-i2v", label: "LTX 2.5 Image to Video", provider: "Lightricks", category: "video",
    mode: "i2v", endpoint: "ltx-2.5-image-to-video", imageInputKey: "image_url", maxReferences: 1,
    supportsStartEndFrame: true, endFrameFieldName: "last_image", badge: "New",
    tagline: "Animate a frame up to 4K with optional last frame",
  },
  {
    id: "flux-3-video-extend", label: "Flux 3 Video Extend", provider: "Black Forest Labs",
    category: "video", mode: "v2v", endpoint: "flux-3-video-extend", maxReferences: 0,
    requiresVideoInput: true, supportsKeepSound: false,
    aspectRatios: MUSE_RATIOS, defaultAspectRatio: "16:9", badge: "New",
    tagline: "Extend a video using a text instruction",
  },
  {
    id: "wan3-spicy-reference", label: "Wan 3.0 Spicy Reference to Video", provider: "Wan",
    category: "video", mode: "omni", endpoint: "wan3.0-spicy-reference-to-video",
    imageInputKey: "images_list", maxReferences: 10,
    aspectRatios: ["adaptive", "16:9", "9:16", "1:1", "4:3", "3:4"],
    defaultAspectRatio: "adaptive", badge: "New",
    tagline: "Mix image, video and audio references",
  },
  {
    id: "seedance-2-mini-spicy-omni", label: "Seedance 2 Mini Spicy Omni", provider: "ByteDance",
    category: "video", mode: "omni", endpoint: "seedance-2-mini-spicy-omni-reference",
    imageInputKey: "images_list", maxReferences: 9,
    aspectRatios: ["16:9", "9:16", "1:1", "3:4", "4:3", "21:9"],
    defaultAspectRatio: "16:9", badge: "New",
    tagline: "Affordable video with image, video and audio references",
  },
  ...(["", "-fast"] as const).map((variant) => ({
    id: `seedance-2-spicy-omni${variant}`,
    label: `Seedance 2 Spicy Omni${variant ? " Fast" : ""}`,
    provider: "ByteDance", category: "video" as const, mode: "omni" as const,
    endpoint: `seedance-2-spicy-omni-reference${variant}`,
    imageInputKey: "images_list" as const, maxReferences: 9,
    aspectRatios: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
    defaultAspectRatio: "16:9", badge: "New", tagline: "Reference-driven video with priority routing",
  })),
  {
    id: "seedance-2.5-spicy-omni", label: "Seedance 2.5 Spicy Omni", provider: "ByteDance",
    category: "video", mode: "omni", endpoint: "seedance-2.5-spicy-omni-reference",
    imageInputKey: "images_list", maxReferences: 30,
    aspectRatios: ["adaptive", "16:9", "9:16", "1:1", "4:3", "3:4", "21:9", "9:21"],
    defaultAspectRatio: "adaptive", badge: "New",
    tagline: "Multi-reference video with selectable resolution",
  },
  ...(["seedance-2-motion-control", "seedance-2.5-motion-control", "seedance-2.5-intl-motion-control", "seedance-2.5-spicy-motion-control"] as const).map((endpoint) => ({
    id: endpoint, label: endpoint.replaceAll("-", " ").replace("seedance", "Seedance").replace("motion control", "Motion Control"),
    provider: "ByteDance", category: "video" as const, mode: "v2v" as const,
    endpoint, maxReferences: endpoint.startsWith("seedance-2.5") ? 30 : 9,
    requiresReferenceInput: true,
    requiresVideoInput: true, supportsKeepSound: false, badge: "New",
    tagline: "Recast a performance while preserving its motion",
  })),
] as ModelConfig[]).map((model) => ({ ...model, catalogBaseCostUsd: CATALOG_BASE_COST_USD[model.endpoint] }));
